/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen.tables;


import com.sh.jooq.codegen.Keys;
import com.sh.jooq.codegen.Security;
import com.sh.jooq.codegen.tables.records.TMenuRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMenu extends TableImpl<TMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security.t_menu</code>
     */
    public static final TMenu T_MENU = new TMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TMenuRecord> getRecordType() {
        return TMenuRecord.class;
    }

    /**
     * The column <code>security.t_menu.id</code>.
     */
    public final TableField<TMenuRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>security.t_menu.pattern</code>.
     */
    public final TableField<TMenuRecord, String> PATTERN = createField(DSL.name("pattern"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private TMenu(Name alias, Table<TMenuRecord> aliased) {
        this(alias, aliased, null);
    }

    private TMenu(Name alias, Table<TMenuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>security.t_menu</code> table reference
     */
    public TMenu(String alias) {
        this(DSL.name(alias), T_MENU);
    }

    /**
     * Create an aliased <code>security.t_menu</code> table reference
     */
    public TMenu(Name alias) {
        this(alias, T_MENU);
    }

    /**
     * Create a <code>security.t_menu</code> table reference
     */
    public TMenu() {
        this(DSL.name("t_menu"), null);
    }

    public <O extends Record> TMenu(Table<O> child, ForeignKey<O, TMenuRecord> key) {
        super(child, key, T_MENU);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Security.SECURITY;
    }

    @Override
    public Identity<TMenuRecord, Long> getIdentity() {
        return (Identity<TMenuRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TMenuRecord> getPrimaryKey() {
        return Keys.KEY_T_MENU_PRIMARY;
    }

    @Override
    public TMenu as(String alias) {
        return new TMenu(DSL.name(alias), this);
    }

    @Override
    public TMenu as(Name alias) {
        return new TMenu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TMenu rename(String name) {
        return new TMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TMenu rename(Name name) {
        return new TMenu(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
