/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen.tables;


import com.sh.jooq.codegen.Keys;
import com.sh.jooq.codegen.Security;
import com.sh.jooq.codegen.tables.records.TUserRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser extends TableImpl<TUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security.t_user</code>
     */
    public static final TUser T_USER = new TUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserRecord> getRecordType() {
        return TUserRecord.class;
    }

    /**
     * The column <code>security.t_user.id</code>.
     */
    public final TableField<TUserRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>security.t_user.account_non_expired</code>.
     */
    public final TableField<TUserRecord, Boolean> ACCOUNT_NON_EXPIRED = createField(DSL.name("account_non_expired"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'1'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>security.t_user.account_non_locked</code>.
     */
    public final TableField<TUserRecord, Boolean> ACCOUNT_NON_LOCKED = createField(DSL.name("account_non_locked"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'1'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>security.t_user.credentials_non_expired</code>.
     */
    public final TableField<TUserRecord, Boolean> CREDENTIALS_NON_EXPIRED = createField(DSL.name("credentials_non_expired"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'1'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>security.t_user.enabled</code>.
     */
    public final TableField<TUserRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BIT.nullable(false).defaultValue(DSL.inline("b'1'", SQLDataType.BIT)), this, "");

    /**
     * The column <code>security.t_user.password</code>.
     */
    public final TableField<TUserRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>security.t_user.username</code>.
     */
    public final TableField<TUserRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>security.t_user.secret_key</code>.
     */
    public final TableField<TUserRecord, String> SECRET_KEY = createField(DSL.name("secret_key"), SQLDataType.VARCHAR(100), this, "");

    private TUser(Name alias, Table<TUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUser(Name alias, Table<TUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>security.t_user</code> table reference
     */
    public TUser(String alias) {
        this(DSL.name(alias), T_USER);
    }

    /**
     * Create an aliased <code>security.t_user</code> table reference
     */
    public TUser(Name alias) {
        this(alias, T_USER);
    }

    /**
     * Create a <code>security.t_user</code> table reference
     */
    public TUser() {
        this(DSL.name("t_user"), null);
    }

    public <O extends Record> TUser(Table<O> child, ForeignKey<O, TUserRecord> key) {
        super(child, key, T_USER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Security.SECURITY;
    }

    @Override
    public Identity<TUserRecord, Long> getIdentity() {
        return (Identity<TUserRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TUserRecord> getPrimaryKey() {
        return Keys.KEY_T_USER_PRIMARY;
    }

//    @Override
    public List<UniqueKey<TUserRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_T_USER_T_USER_UN);
    }

    @Override
    public TUser as(String alias) {
        return new TUser(DSL.name(alias), this);
    }

    @Override
    public TUser as(Name alias) {
        return new TUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUser rename(String name) {
        return new TUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TUser rename(Name name) {
        return new TUser(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Boolean, Boolean, Boolean, Boolean, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
