/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen;


import com.sh.jooq.codegen.tables.Authorities;
import com.sh.jooq.codegen.tables.PersistentLogins;
import com.sh.jooq.codegen.tables.TMenu;
import com.sh.jooq.codegen.tables.TRole;
import com.sh.jooq.codegen.tables.TRoleMenu;
import com.sh.jooq.codegen.tables.TUser;
import com.sh.jooq.codegen.tables.TUserRoles;
import com.sh.jooq.codegen.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Security extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>security</code>
     */
    public static final Security SECURITY = new Security();

    /**
     * The table <code>security.authorities</code>.
     */
    public final Authorities AUTHORITIES = Authorities.AUTHORITIES;

    /**
     * The table <code>security.persistent_logins</code>.
     */
    public final PersistentLogins PERSISTENT_LOGINS = PersistentLogins.PERSISTENT_LOGINS;

    /**
     * The table <code>security.t_menu</code>.
     */
    public final TMenu T_MENU = TMenu.T_MENU;

    /**
     * The table <code>security.t_role</code>.
     */
    public final TRole T_ROLE = TRole.T_ROLE;

    /**
     * The table <code>security.t_role_menu</code>.
     */
    public final TRoleMenu T_ROLE_MENU = TRoleMenu.T_ROLE_MENU;

    /**
     * The table <code>security.t_user</code>.
     */
    public final TUser T_USER = TUser.T_USER;

    /**
     * The table <code>security.t_user_roles</code>.
     */
    public final TUserRoles T_USER_ROLES = TUserRoles.T_USER_ROLES;

    /**
     * The table <code>security.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Security() {
        super("security", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Authorities.AUTHORITIES,
            PersistentLogins.PERSISTENT_LOGINS,
            TMenu.T_MENU,
            TRole.T_ROLE,
            TRoleMenu.T_ROLE_MENU,
            TUser.T_USER,
            TUserRoles.T_USER_ROLES,
            Users.USERS
        );
    }
}
