/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen;


import com.sh.jooq.codegen.tables.Authorities;
import com.sh.jooq.codegen.tables.PersistentLogins;
import com.sh.jooq.codegen.tables.TMenu;
import com.sh.jooq.codegen.tables.TRole;
import com.sh.jooq.codegen.tables.TRoleMenu;
import com.sh.jooq.codegen.tables.TUser;
import com.sh.jooq.codegen.tables.TUserRoles;
import com.sh.jooq.codegen.tables.Users;


/**
 * Convenience access to all tables in security.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>security.authorities</code>.
     */
    public static final Authorities AUTHORITIES = Authorities.AUTHORITIES;

    /**
     * The table <code>security.persistent_logins</code>.
     */
    public static final PersistentLogins PERSISTENT_LOGINS = PersistentLogins.PERSISTENT_LOGINS;

    /**
     * The table <code>security.t_menu</code>.
     */
    public static final TMenu T_MENU = TMenu.T_MENU;

    /**
     * The table <code>security.t_role</code>.
     */
    public static final TRole T_ROLE = TRole.T_ROLE;

    /**
     * The table <code>security.t_role_menu</code>.
     */
    public static final TRoleMenu T_ROLE_MENU = TRoleMenu.T_ROLE_MENU;

    /**
     * The table <code>security.t_user</code>.
     */
    public static final TUser T_USER = TUser.T_USER;

    /**
     * The table <code>security.t_user_roles</code>.
     */
    public static final TUserRoles T_USER_ROLES = TUserRoles.T_USER_ROLES;

    /**
     * The table <code>security.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
