/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen.tables.records;


import com.sh.jooq.codegen.tables.TRoleMenu;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleMenuRecord extends UpdatableRecordImpl<TRoleMenuRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.t_role_menu.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>security.t_role_menu.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>security.t_role_menu.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>security.t_role_menu.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>security.t_role_menu.menu_id</code>.
     */
    public void setMenuId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>security.t_role_menu.menu_id</code>.
     */
    public Long getMenuId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TRoleMenu.T_ROLE_MENU.ID;
    }

    @Override
    public Field<Long> field2() {
        return TRoleMenu.T_ROLE_MENU.ROLE_ID;
    }

    @Override
    public Field<Long> field3() {
        return TRoleMenu.T_ROLE_MENU.MENU_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getRoleId();
    }

    @Override
    public Long component3() {
        return getMenuId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getRoleId();
    }

    @Override
    public Long value3() {
        return getMenuId();
    }

    @Override
    public TRoleMenuRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TRoleMenuRecord value2(Long value) {
        setRoleId(value);
        return this;
    }

    @Override
    public TRoleMenuRecord value3(Long value) {
        setMenuId(value);
        return this;
    }

    @Override
    public TRoleMenuRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TRoleMenuRecord
     */
    public TRoleMenuRecord() {
        super(TRoleMenu.T_ROLE_MENU);
    }

    /**
     * Create a detached, initialised TRoleMenuRecord
     */
    public TRoleMenuRecord(Long id, Long roleId, Long menuId) {
        super(TRoleMenu.T_ROLE_MENU);

        setId(id);
        setRoleId(roleId);
        setMenuId(menuId);
    }

    /**
     * Create a detached, initialised TRoleMenuRecord
     */
    public TRoleMenuRecord(com.sh.jooq.codegen.tables.pojos.TRoleMenu value) {
        super(TRoleMenu.T_ROLE_MENU);

        if (value != null) {
            setId(value.getId());
            setRoleId(value.getRoleId());
            setMenuId(value.getMenuId());
        }
    }
}
