/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen.tables.records;


import com.sh.jooq.codegen.tables.TUserRoles;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRolesRecord extends TableRecordImpl<TUserRolesRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>security.t_user_roles.t_user_id</code>.
     */
    public void setTUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>security.t_user_roles.t_user_id</code>.
     */
    public Long getTUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>security.t_user_roles.roles_id</code>.
     */
    public void setRolesId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>security.t_user_roles.roles_id</code>.
     */
    public Long getRolesId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TUserRoles.T_USER_ROLES.T_USER_ID;
    }

    @Override
    public Field<Long> field2() {
        return TUserRoles.T_USER_ROLES.ROLES_ID;
    }

    @Override
    public Long component1() {
        return getTUserId();
    }

    @Override
    public Long component2() {
        return getRolesId();
    }

    @Override
    public Long value1() {
        return getTUserId();
    }

    @Override
    public Long value2() {
        return getRolesId();
    }

    @Override
    public TUserRolesRecord value1(Long value) {
        setTUserId(value);
        return this;
    }

    @Override
    public TUserRolesRecord value2(Long value) {
        setRolesId(value);
        return this;
    }

    @Override
    public TUserRolesRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserRolesRecord
     */
    public TUserRolesRecord() {
        super(TUserRoles.T_USER_ROLES);
    }

    /**
     * Create a detached, initialised TUserRolesRecord
     */
    public TUserRolesRecord(Long tUserId, Long rolesId) {
        super(TUserRoles.T_USER_ROLES);

        setTUserId(tUserId);
        setRolesId(rolesId);
    }

    /**
     * Create a detached, initialised TUserRolesRecord
     */
    public TUserRolesRecord(com.sh.jooq.codegen.tables.pojos.TUserRoles value) {
        super(TUserRoles.T_USER_ROLES);

        if (value != null) {
            setTUserId(value.getTUserId());
            setRolesId(value.getRolesId());
        }
    }
}
