/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authorities implements Serializable {

    private static final long serialVersionUID = 1L;

    private String username;
    private String authority;

    public Authorities() {}

    public Authorities(Authorities value) {
        this.username = value.username;
        this.authority = value.authority;
    }

    public Authorities(
        String username,
        String authority
    ) {
        this.username = username;
        this.authority = authority;
    }

    /**
     * Getter for <code>security.authorities.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>security.authorities.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>security.authorities.authority</code>.
     */
    public String getAuthority() {
        return this.authority;
    }

    /**
     * Setter for <code>security.authorities.authority</code>.
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Authorities (");

        sb.append(username);
        sb.append(", ").append(authority);

        sb.append(")");
        return sb.toString();
    }
}
