/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersistentLogins implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        username;
    private String        series;
    private String        token;
    private LocalDateTime lastUsed;

    public PersistentLogins() {}

    public PersistentLogins(PersistentLogins value) {
        this.username = value.username;
        this.series = value.series;
        this.token = value.token;
        this.lastUsed = value.lastUsed;
    }

    public PersistentLogins(
        String        username,
        String        series,
        String        token,
        LocalDateTime lastUsed
    ) {
        this.username = username;
        this.series = series;
        this.token = token;
        this.lastUsed = lastUsed;
    }

    /**
     * Getter for <code>security.persistent_logins.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>security.persistent_logins.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>security.persistent_logins.series</code>.
     */
    public String getSeries() {
        return this.series;
    }

    /**
     * Setter for <code>security.persistent_logins.series</code>.
     */
    public void setSeries(String series) {
        this.series = series;
    }

    /**
     * Getter for <code>security.persistent_logins.token</code>.
     */
    public String getToken() {
        return this.token;
    }

    /**
     * Setter for <code>security.persistent_logins.token</code>.
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * Getter for <code>security.persistent_logins.last_used</code>.
     */
    public LocalDateTime getLastUsed() {
        return this.lastUsed;
    }

    /**
     * Setter for <code>security.persistent_logins.last_used</code>.
     */
    public void setLastUsed(LocalDateTime lastUsed) {
        this.lastUsed = lastUsed;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PersistentLogins (");

        sb.append(username);
        sb.append(", ").append(series);
        sb.append(", ").append(token);
        sb.append(", ").append(lastUsed);

        sb.append(")");
        return sb.toString();
    }
}
