/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMenu implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String pattern;

    public TMenu() {}

    public TMenu(TMenu value) {
        this.id = value.id;
        this.pattern = value.pattern;
    }

    public TMenu(
        Long   id,
        String pattern
    ) {
        this.id = id;
        this.pattern = pattern;
    }

    /**
     * Getter for <code>security.t_menu.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>security.t_menu.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>security.t_menu.pattern</code>.
     */
    public String getPattern() {
        return this.pattern;
    }

    /**
     * Setter for <code>security.t_menu.pattern</code>.
     */
    public void setPattern(String pattern) {
        this.pattern = pattern;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TMenu (");

        sb.append(id);
        sb.append(", ").append(pattern);

        sb.append(")");
        return sb.toString();
    }
}
