/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TRoleMenu implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long roleId;
    private Long menuId;

    public TRoleMenu() {}

    public TRoleMenu(TRoleMenu value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.menuId = value.menuId;
    }

    public TRoleMenu(
        Long id,
        Long roleId,
        Long menuId
    ) {
        this.id = id;
        this.roleId = roleId;
        this.menuId = menuId;
    }

    /**
     * Getter for <code>security.t_role_menu.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>security.t_role_menu.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>security.t_role_menu.role_id</code>.
     */
    public Long getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>security.t_role_menu.role_id</code>.
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * Getter for <code>security.t_role_menu.menu_id</code>.
     */
    public Long getMenuId() {
        return this.menuId;
    }

    /**
     * Setter for <code>security.t_role_menu.menu_id</code>.
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TRoleMenu (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(menuId);

        sb.append(")");
        return sb.toString();
    }
}
