/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private Boolean accountNonExpired;
    private Boolean accountNonLocked;
    private Boolean credentialsNonExpired;
    private Boolean enabled;
    private String  password;
    private String  username;
    private String  secretKey;

    public TUser() {}

    public TUser(TUser value) {
        this.id = value.id;
        this.accountNonExpired = value.accountNonExpired;
        this.accountNonLocked = value.accountNonLocked;
        this.credentialsNonExpired = value.credentialsNonExpired;
        this.enabled = value.enabled;
        this.password = value.password;
        this.username = value.username;
        this.secretKey = value.secretKey;
    }

    public TUser(
        Long    id,
        Boolean accountNonExpired,
        Boolean accountNonLocked,
        Boolean credentialsNonExpired,
        Boolean enabled,
        String  password,
        String  username,
        String  secretKey
    ) {
        this.id = id;
        this.accountNonExpired = accountNonExpired;
        this.accountNonLocked = accountNonLocked;
        this.credentialsNonExpired = credentialsNonExpired;
        this.enabled = enabled;
        this.password = password;
        this.username = username;
        this.secretKey = secretKey;
    }

    /**
     * Getter for <code>security.t_user.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>security.t_user.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>security.t_user.account_non_expired</code>.
     */
    public Boolean getAccountNonExpired() {
        return this.accountNonExpired;
    }

    /**
     * Setter for <code>security.t_user.account_non_expired</code>.
     */
    public void setAccountNonExpired(Boolean accountNonExpired) {
        this.accountNonExpired = accountNonExpired;
    }

    /**
     * Getter for <code>security.t_user.account_non_locked</code>.
     */
    public Boolean getAccountNonLocked() {
        return this.accountNonLocked;
    }

    /**
     * Setter for <code>security.t_user.account_non_locked</code>.
     */
    public void setAccountNonLocked(Boolean accountNonLocked) {
        this.accountNonLocked = accountNonLocked;
    }

    /**
     * Getter for <code>security.t_user.credentials_non_expired</code>.
     */
    public Boolean getCredentialsNonExpired() {
        return this.credentialsNonExpired;
    }

    /**
     * Setter for <code>security.t_user.credentials_non_expired</code>.
     */
    public void setCredentialsNonExpired(Boolean credentialsNonExpired) {
        this.credentialsNonExpired = credentialsNonExpired;
    }

    /**
     * Getter for <code>security.t_user.enabled</code>.
     */
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>security.t_user.enabled</code>.
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Getter for <code>security.t_user.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>security.t_user.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>security.t_user.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>security.t_user.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>security.t_user.secret_key</code>.
     */
    public String getSecretKey() {
        return this.secretKey;
    }

    /**
     * Setter for <code>security.t_user.secret_key</code>.
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUser (");

        sb.append(id);
        sb.append(", ").append(accountNonExpired);
        sb.append(", ").append(accountNonLocked);
        sb.append(", ").append(credentialsNonExpired);
        sb.append(", ").append(enabled);
        sb.append(", ").append(password);
        sb.append(", ").append(username);
        sb.append(", ").append(secretKey);

        sb.append(")");
        return sb.toString();
    }
}
