/*
 * This file is generated by jOOQ.
 */
package com.sh.jooq.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRoles implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long tUserId;
    private Long rolesId;

    public TUserRoles() {}

    public TUserRoles(TUserRoles value) {
        this.tUserId = value.tUserId;
        this.rolesId = value.rolesId;
    }

    public TUserRoles(
        Long tUserId,
        Long rolesId
    ) {
        this.tUserId = tUserId;
        this.rolesId = rolesId;
    }

    /**
     * Getter for <code>security.t_user_roles.t_user_id</code>.
     */
    public Long getTUserId() {
        return this.tUserId;
    }

    /**
     * Setter for <code>security.t_user_roles.t_user_id</code>.
     */
    public void setTUserId(Long tUserId) {
        this.tUserId = tUserId;
    }

    /**
     * Getter for <code>security.t_user_roles.roles_id</code>.
     */
    public Long getRolesId() {
        return this.rolesId;
    }

    /**
     * Setter for <code>security.t_user_roles.roles_id</code>.
     */
    public void setRolesId(Long rolesId) {
        this.rolesId = rolesId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUserRoles (");

        sb.append(tUserId);
        sb.append(", ").append(rolesId);

        sb.append(")");
        return sb.toString();
    }
}
